import type { CoinTheme } from './index'

export const COIN_THEMES: CoinTheme[] = [
  {
    id: 'gold',
    label: 'Gold',
    emoji: '🥇',
    colors: {
      // Front of coin
      shadow: '#D97706',
      main: '#FBBF24',
      highlight: '#FCD34D',
      ring: '#D97706',
      rimHighlight: '#FDE68A',
      textColor: 'text-amber-900',
      // Back of coin
      backShadow: '#B45309',
      backMain: '#F59E0B',
      backHighlight: '#FBBF24',
      backPattern: '#D97706',
      backRing: '#92400E',
      backRimHighlight: '#FCD34D',
    },
  },
  {
    id: 'silver',
    label: 'Silver',
    emoji: '🥈',
    colors: {
      shadow: '#6B7280',
      main: '#D1D5DB',
      highlight: '#F3F4F6',
      ring: '#9CA3AF',
      rimHighlight: '#F9FAFB',
      textColor: 'text-gray-700',
      backShadow: '#4B5563',
      backMain: '#9CA3AF',
      backHighlight: '#D1D5DB',
      backPattern: '#6B7280',
      backRing: '#374151',
      backRimHighlight: '#E5E7EB',
    },
  },
  {
    id: 'bronze',
    label: 'Bronze',
    emoji: '🥉',
    colors: {
      shadow: '#92400E',
      main: '#D97706',
      highlight: '#F59E0B',
      ring: '#78350F',
      rimHighlight: '#FBBF24',
      textColor: 'text-amber-950',
      backShadow: '#78350F',
      backMain: '#B45309',
      backHighlight: '#D97706',
      backPattern: '#92400E',
      backRing: '#451A03',
      backRimHighlight: '#F59E0B',
    },
  },
  {
    id: 'rose-gold',
    label: 'Rose Gold',
    emoji: '💗',
    colors: {
      shadow: '#BE185D',
      main: '#F472B6',
      highlight: '#FBCFE8',
      ring: '#DB2777',
      rimHighlight: '#FCE7F3',
      textColor: 'text-pink-900',
      backShadow: '#9D174D',
      backMain: '#EC4899',
      backHighlight: '#F472B6',
      backPattern: '#BE185D',
      backRing: '#831843',
      backRimHighlight: '#FBCFE8',
    },
  },
  {
    id: 'crystal',
    label: 'Crystal',
    emoji: '💎',
    colors: {
      shadow: '#6366F1',
      main: '#A5B4FC',
      highlight: '#E0E7FF',
      ring: '#818CF8',
      rimHighlight: '#EEF2FF',
      textColor: 'text-indigo-900',
      backShadow: '#4F46E5',
      backMain: '#818CF8',
      backHighlight: '#A5B4FC',
      backPattern: '#6366F1',
      backRing: '#3730A3',
      backRimHighlight: '#C7D2FE',
    },
  },
]
