import type { WellTheme } from './index'

export const WELL_THEMES: WellTheme[] = [
  {
    id: 'classic',
    label: 'Classic',
    emoji: '🏛️',
    colors: {
      roof: '#E86F22',
      roofAccent: '#D35B38',
      poles: '#FEC45E',
      polesAccent: '#FCDB5A',
      base: '#FCDB5A',
      baseAccent: '#FEC45E',
      rim: '#BCC987',
      rimAccent: '#9CAC74',
      rope: '#4D3D36',
      grass: '#BCC987',
    },
  },
  {
    id: 'rose-garden',
    label: 'Rose Garden',
    emoji: '🌹',
    colors: {
      roof: '#F472B6',
      roofAccent: '#DB2777',
      poles: '#FDE68A',
      polesAccent: '#FCD34D',
      base: '#FBCFE8',
      baseAccent: '#F9A8D4',
      rim: '#86EFAC',
      rimAccent: '#4ADE80',
      rope: '#831843',
      grass: '#86EFAC',
    },
  },
  {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    colors: {
      roof: '#0EA5E9',
      roofAccent: '#0284C7',
      poles: '#BAE6FD',
      polesAccent: '#7DD3FC',
      base: '#E0F2FE',
      baseAccent: '#BAE6FD',
      rim: '#5EEAD4',
      rimAccent: '#2DD4BF',
      rope: '#164E63',
      grass: '#5EEAD4',
    },
  },
  {
    id: 'sunset',
    label: 'Sunset',
    emoji: '🌅',
    colors: {
      roof: '#F97316',
      roofAccent: '#EA580C',
      poles: '#FCD34D',
      polesAccent: '#FBBF24',
      base: '#C4B5FD',
      baseAccent: '#A78BFA',
      rim: '#FDBA74',
      rimAccent: '#FB923C',
      rope: '#7C2D12',
      grass: '#FDE68A',
    },
  },
  {
    id: 'forest',
    label: 'Forest',
    emoji: '🌲',
    colors: {
      roof: '#166534',
      roofAccent: '#14532D',
      poles: '#A16207',
      polesAccent: '#854D0E',
      base: '#D6D3D1',
      baseAccent: '#A8A29E',
      rim: '#4ADE80',
      rimAccent: '#22C55E',
      rope: '#422006',
      grass: '#86EFAC',
    },
  },
  {
    id: 'midnight',
    label: 'Midnight',
    emoji: '🌙',
    colors: {
      roof: '#1E3A8A',
      roofAccent: '#1E40AF',
      poles: '#94A3B8',
      polesAccent: '#64748B',
      base: '#334155',
      baseAccent: '#1E293B',
      rim: '#CBD5E1',
      rimAccent: '#94A3B8',
      rope: '#0F172A',
      grass: '#475569',
    },
  },
]
